proxy:
  name: proxy 
  labels:
    app: proxy
    env: dev
    stack: proxy
  image:
    repository: nginx
    tag: latest
    pullPolicy: Always
  replicas: 3
  configmap:
    ## KEY: "value"
    APP_ENV: "dev"

  containerPorts:
      http: 80
