proxy:
  name: proxy 
  labels:
    app: proxy
    env: dev
    stack: proxy
  image:
    repository: naadjaa/icaimage
    tag: latest
    pullPolicy: Always
  replicas: 1
  configmap:
    ## KEY: "value"
    APP_ENV: "dev"

  containerPorts:
      http: 80
